# Generated by Django 5.2.5 on 2025-08-14 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_watchlist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlistitem',
            name='added_at',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='exchange',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
